#include "hbmsim/hbm_system.h"

#include <cassert>
#include <vector>

namespace {

hbmsim::HbmConfig base_config() {
  hbmsim::HbmConfig config;
  config.topology.pseudo_channels_per_channel = 1;
  config.topology.bank_groups_per_pseudo_channel = 1;
  config.topology.banks_per_bank_group = 1;
  config.address_interleave_bytes = 64;
  config.columns_per_row = 2;
  config.rows_per_bank = 8;
  config.channel_bandwidth_bytes_per_ns = 1000;
  config.timing.t_rcd = 10;
  config.timing.t_rp = 5;
  config.timing.t_cl = 20;
  config.timing.t_ras = 0;
  config.timing.t_rc = 0;
  config.timing.t_ccd = 0;
  config.timing.t_rrd = 0;
  config.timing.t_faw = 0;
  config.timing.t_wtr = 0;
  config.timing.t_rtw = 0;
  config.timing.t_rfc = 100;
  return config;
}

}  // namespace

int main() {
  // H2: a closed-row request plans ACT then waits tRCD before RD.
  {
    hbmsim::HbmSystem system(base_config());
    assert(system.submit({1, hbmsim::HbmOp::Read, 0, 64, 0, 0}).accepted());
    system.run();
    assert(system.completions().size() == 1);
    assert(system.completions()[0].completion_time == 94);  // 10 + 20 + 64 ps
    assert(system.stats().issued_commands == 2);
    assert(system.stats().row_closed == 1);
  }

  // H2: hit, closed, and conflict are generated by actual command sequences.
  {
    hbmsim::HbmSystem system(base_config());
    assert(system.submit({1, hbmsim::HbmOp::Read, 0, 64, 0, 0}).accepted());
    assert(system.submit({2, hbmsim::HbmOp::Read, 64, 64, 100, 0}).accepted());
    assert(system.submit({3, hbmsim::HbmOp::Read, 128, 64, 200, 0}).accepted());
    system.run();
    const auto& completions = system.completions();
    assert(completions.size() == 3);
    assert(completions[0].access_class == hbmsim::HbmAccessClass::RowClosed);
    assert(completions[1].access_class == hbmsim::HbmAccessClass::RowHit);
    assert(completions[2].access_class == hbmsim::HbmAccessClass::RowConflict);
    assert(completions[0].completion_time == 94);
    assert(completions[1].completion_time == 184);
    assert(completions[2].completion_time == 299);
    assert(system.stats().row_closed == 1);
    assert(system.stats().row_hits == 1);
    assert(system.stats().row_conflicts == 1);
  }

  // H3: FR-FCFS keeps a row hit ahead of an older row-conflict request.
  {
    hbmsim::HbmSystem system(base_config());
    std::vector<hbmsim::TransactionId> completion_order;
    system.set_completion_callback(
        [&](const hbmsim::HbmCompletion& completion) { completion_order.push_back(completion.id); });
    assert(system.submit({1, hbmsim::HbmOp::Read, 0, 64, 0, 0}).accepted());
    assert(system.submit({2, hbmsim::HbmOp::Read, 128, 64, 100, 0}).accepted());
    assert(system.submit({3, hbmsim::HbmOp::Read, 64, 64, 100, 0}).accepted());
    system.run();
    assert((completion_order == std::vector<hbmsim::TransactionId>{1, 3, 2}));
    assert(system.completions()[1].access_class == hbmsim::HbmAccessClass::RowHit);
  }

  // H3: a write queue at its high watermark is drained before reads.
  {
    auto config = base_config();
    config.write_drain_high_watermark = 1;
    config.write_drain_low_watermark = 0;
    hbmsim::HbmSystem system(config);
    std::vector<hbmsim::TransactionId> completion_order;
    system.set_completion_callback(
        [&](const hbmsim::HbmCompletion& completion) { completion_order.push_back(completion.id); });
    assert(system.submit({1, hbmsim::HbmOp::Read, 0, 64, 0, 0}).accepted());
    assert(system.submit({2, hbmsim::HbmOp::Write, 64, 64, 0, 0}).accepted());
    system.run();
    assert(completion_order.front() == 2);
  }

  // H4: all-bank refresh blocks the controller for tRFC before queued work.
  {
    auto config = base_config();
    config.refresh_interval = 100;
    config.timing.t_rcd = 1000;
    hbmsim::HbmSystem system(config);
    assert(system.submit({1, hbmsim::HbmOp::Read, 0, 64, 0, 0}).accepted());
    assert(system.submit({2, hbmsim::HbmOp::Read, 64, 64, 2, 0}).accepted());
    system.run_until(150);
    assert(system.stats().channels[0].refreshes == 1);
    assert(system.stats().completed_transactions == 0);
  }

  // H5: 16 KiB is represented by four 4 KiB accesses, never 256 64 B bursts.
  {
    auto config = base_config();
    config.address_interleave_bytes = 4096;
    config.simulation_access_granularity_bytes = 4096;
    config.timing.t_rcd = 0;
    config.timing.t_cl = 0;
    config.channel_bandwidth_bytes_per_ns = 100'000;
    hbmsim::HbmSystem system(config);
    assert(system.submit({1, hbmsim::HbmOp::Read, 0, 16 * 1024, 0, 0}).accepted());
    system.run();
    assert(system.stats().modeled_accesses == 4);
    assert(system.stats().completed_transactions == 1);
    assert(system.stats().read_bytes == 16 * 1024);
    assert(system.stats().channels[0].completed_bytes == 16 * 1024);
    assert(system.stats().channels[0].data_bus_busy_time == 164);
  }
}
